---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

# lint: |
#   yamllint .
#   ansible-lint -v .

platforms:
  - name: alma8
    box: bento/almalinux-8
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.8"
  - name: alma9
    box: bento/almalinux-9
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.9"

provisioner:
  name: ansible

verifier:
  name: ansible
